### PR TITLE
29 move random selection from dataset to preprocessing pipeline

### PR DESCRIPTION
**Pull request by jkarolczak**

### CODE REVIEW

**Comment by jkarolczak** [comment]
@konradszewczyk I know that I disappointed you not asking for a review before. Could you review this PR?
please

**Review by wtaisner — APPROVED** [review]
Sorry, @konradszewczyk , it is obviously Jacek's fault once again

**Comment by konradszewczyk** [comment]
@jkarolczak, now I am feeling 100% offended by your actions - shame on you!

**Comment by wtaisner** [comment]
gif

**Comment by jkarolczak** [comment]
I'm so sorry...
embarassed

**Pull request merged**
